// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTGdDDSVIOUAsh96lHL_fs8taLtDGFQhk',
    appId: '1:757949910153:web:455662f06af80ba7594a58',
    messagingSenderId: '757949910153',
    projectId: 'globox-9b65a',
    authDomain: 'globox-9b65a.firebaseapp.com',
    storageBucket: 'globox-9b65a.firebasestorage.app',
    measurementId: 'G-0BJWNNKL68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkmxXVh7V-NMGRDpexmZYE4q0ukDsdkEY',
    appId: '1:757949910153:android:eb6af57438346e6c594a58',
    messagingSenderId: '757949910153',
    projectId: 'globox-9b65a',
    storageBucket: 'globox-9b65a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdCb08qT2bcvkAbZwMoe-JCCazAUr8hA',
    appId: '1:757949910153:ios:927cc728a280db7b594a58',
    messagingSenderId: '757949910153',
    projectId: 'globox-9b65a',
    storageBucket: 'globox-9b65a.firebasestorage.app',
    iosBundleId: 'com.example.globox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdCb08qT2bcvkAbZwMoe-JCCazAUr8hA',
    appId: '1:757949910153:ios:927cc728a280db7b594a58',
    messagingSenderId: '757949910153',
    projectId: 'globox-9b65a',
    storageBucket: 'globox-9b65a.firebasestorage.app',
    iosBundleId: 'com.example.globox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTGdDDSVIOUAsh96lHL_fs8taLtDGFQhk',
    appId: '1:757949910153:web:7fb64a907255b58c594a58',
    messagingSenderId: '757949910153',
    projectId: 'globox-9b65a',
    authDomain: 'globox-9b65a.firebaseapp.com',
    storageBucket: 'globox-9b65a.firebasestorage.app',
    measurementId: 'G-9QQNGF0QW5',
  );
}
